import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import {
  ClerkProvider,
  SignInButton,
  SignUpButton,
  SignedIn,
  SignedOut,
  UserButton,
} from '@clerk/nextjs'
import Provider from "./Provider.tsx";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ClerkProvider>
      <html lang="en">
        <body
  className={`${geistSans.variable} ${geistMono.variable} antialiased h-screen flex flex-col`}
>

          <header className="flex justify-between items-center px-6 h-16 border-b bg-white dark:bg-black">
            {/* Left - Logo */}
            <div className="flex items-center gap-2 font-semibold text-lg">
              <div className="w-8 h-8 bg-[#6c47ff] rounded-lg flex items-center justify-center text-white font-bold">
                AI
              </div>
              ResumeAI
            </div>

            {/* Right - Auth Buttons */}
            <div className="flex items-center gap-4">
              <SignedOut>
                <SignInButton />
                <SignUpButton>
                  <button className="bg-[#6c47ff] text-white rounded-full font-medium text-sm h-10 px-5 cursor-pointer">
                    Sign Up
                  </button>
                </SignUpButton>
              </SignedOut>

              <SignedIn>
                <UserButton />
              </SignedIn>
            </div>
          </header>
          <div className="flex-1 overflow-hidden">
            <Provider>
              {children}
            </Provider>
          </div>
        </body>
      </html>
    </ClerkProvider>
  );
}
